# Generated by Django 5.2.16 on 2026-07-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_collection_document_userprofile_delete_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='ai_caption',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='document',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
