# Generated by Django 5.2.16 on 2026-07-12 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_document_ai_caption_document_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='ai_flashcards',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='ai_quiz',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
