# Generated by Django 5.2.16 on 2026-07-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_userprofile_is_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='auto_pay',
            field=models.BooleanField(default=False),
        ),
    ]
