# Generated by Django 5.2.16 on 2026-07-13 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_userprofile_auto_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_chunked',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField(default=1)),
                ('chunk_index', models.IntegerField(default=0)),
                ('text', models.TextField()),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('concept_label', models.CharField(blank=True, default='', max_length=200)),
                ('importance_score', models.FloatField(default=0.5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='myapp.document')),
            ],
            options={
                'ordering': ['page_number', 'chunk_index'],
                'indexes': [models.Index(fields=['document', 'page_number'], name='myapp_docum_documen_64fcf1_idx')],
            },
        ),
    ]
